### PR TITLE
Add pip support

### PR DESCRIPTION
**Pull request by afer92**

### CODE REVIEW

**Comment by afer92** [comment]
sudo pip3 install LMSTools

**Comment by dalgwen** [comment]
Hello, thanks for the PR.
Did you imply that I should publish this fork of LMSTools on PyPI ? (I'm not very familiar with python project lifecycle or packaging tools)
I'm not sure this fork is the best fitted for this ? (It just fits my needs, no pretention). I didn't check or review all other forks, maybe some others are more suitable ?
And I just see the user aschamberger already made a setup.py on his fork a few days ago ? Maybe he does want to publish it.

**Comment by afer92** [comment]
With a setup.py file it is possible to install the module with "sudo pip3 install ." from the module directory.
`git clone https://github.com/aschamberger/LMSTools.git`
`cd LMSTools`
`sudo pip3 install .`

**Comment by dalgwen** [comment]
Great ! Thanks for the explanation.
I merge it now.

**Pull request merged**
